### ISSUE TITLE
Fix Solo angler scoring

### ISSUE THREAD

**Issue by ceegarnut** [envasquez/SABC#118]
Currently, a solo angler that has a blank #2 fisherman, will get zero team points. They do get the individual points. One problem with this...Adam...

**Comment by envasquez** [comment]
I'm not sure if you mean places or points?
Results for individuals get places and points automatically ... because everything is based off of an individual having a result.

Once all of the individual results are entered. You can then create the teams by pairing two anglers (or one angler and a solo -----) the team result (adding result1 + result 2) will then be put in the proper order in the team result table.
